version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/api/Dockerfile
    container_name: api
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./src/.env

  db:
    build:
      context: .
      dockerfile: docker/dev/postgres/Dockerfile
    container_name: djangosearch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env

    ports:
      - 5435:5432

volumes:
  postgres_data:
  static_volume: