version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/dev/api/Dockerfile
    container_name: api
    volumes:
      - ./src:/src
    expose:
      - 8000
    depends_on:
      - db
    command: docker/prod/api/gunicorn.sh
    env_file:
      - ./src/.env.prod

  db:
    build:
      context: .
      dockerfile: docker/prod/postgres/Dockerfile
    container_name: djangosearch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/.env.prod

    expose:
      - 5432
  
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - staticfiles:/home/src/staticfiles
    depends_on:
      - api



volumes:
  postgres_data:
  staticfiles: